# Generated by Django 6.0.5 on 2026-05-23 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short unique code. Example: ICT, VEH, FURN', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(help_text='Unique asset ID. Example: MOH-2024-0001', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Asset name or description', max_length=300)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer serial number if applicable', max_length=100, null=True)),
                ('org_unit_id', models.IntegerField(help_text='ID of the OrgUnit (Facility) where this asset is located')),
                ('org_unit_name', models.CharField(blank=True, help_text='Name snapshot of the org unit — preserved if org unit is renamed', max_length=200)),
                ('location_description', models.CharField(blank=True, help_text='Physical location details. Example: Block A, Room 204', max_length=300)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DECOMMISSIONED', 'Decommissioned'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('CRITICAL', 'Critical')], default='GOOD', max_length=20)),
                ('acquisition_date', models.DateField(blank=True, help_text='Date the asset was acquired', null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase price in Tanzanian Shillings', max_digits=15, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value after depreciation', max_digits=15, null=True)),
                ('funding_source', models.CharField(blank=True, help_text='Where the money came from. Example: Government Budget, Donor', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Any additional notes or details about this asset')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the asset', null=True, upload_to='assets/photos/')),
                ('registered_by_id', models.IntegerField(blank=True, help_text='ID of the user who created this record', null=True)),
                ('registered_by_name', models.CharField(blank=True, help_text='Name snapshot of the user who created this record', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Asset classification', on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
