# Generated by Django 6.0.5 on 2026-05-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_expiry_date',
            field=models.DateField(blank=True, help_text='Date this asset expires or must be replaced. Used for fire extinguishers, medical equipment, licenses etc.', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Company that manufactured this asset. Example: Dell, Toyota', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, help_text='Manufacturer model or product number', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Government procurement PO number for this purchase', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Company or person who supplied this asset to the ministry', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, help_text='Expected useful life in years — used for depreciation calculations', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text='Date the manufacturer warranty expires', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Date the asset was acquired by the ministry', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(help_text='Unique asset ID — auto-generated if left blank', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='funding_source',
            field=models.CharField(blank=True, help_text='Example: Government Budget, World Bank, USAID', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location_description',
            field=models.CharField(blank=True, help_text='Physical location. Example: Block A, Room 204', max_length=300),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='asset',
            name='org_unit_id',
            field=models.IntegerField(blank=True, help_text='ID of the OrgUnit (Facility) where this asset is located', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='org_unit_name',
            field=models.CharField(blank=True, help_text='Name snapshot — preserved if org unit is renamed', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/photos/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='registered_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='registered_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
