# Generated by Django 6.0.5 on 2026-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_asset_expiry_date_asset_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='acquisition_method',
            field=models.CharField(blank=True, help_text='How the asset was obtained. Example: Purchase, Donation', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='cost_centre',
            field=models.CharField(blank=True, help_text='Department responsible for this asset. Example: ICT Department', max_length=100),
        ),
    ]
