# Generated by Django 6.0.5 on 2026-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_acquisition_method_asset_cost_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='disposal_date',
            field=models.DateField(blank=True, help_text='Date the asset was disposed', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_method',
            field=models.CharField(blank=True, help_text='How the asset was disposed. Only filled when status is Disposed.', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_notes',
            field=models.TextField(blank=True, help_text='Notes about the disposal'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_type',
            field=models.CharField(blank=True, help_text='Type of location from master data. Example: Office Building', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_method',
            field=models.CharField(blank=True, help_text='How the asset was obtained. Example: Direct Purchase', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cost_centre',
            field=models.CharField(blank=True, help_text='Department responsible. Example: ICT Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='funding_source',
            field=models.CharField(blank=True, help_text='Where the money came from. Example: Government Budget', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location_description',
            field=models.CharField(blank=True, help_text='Physical location detail. Example: Block A, Room 204', max_length=300),
        ),
    ]
