# Generated by Django 6.0.5 on 2026-05-23 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by_id', models.IntegerField(help_text='ID of the CustomUser who performed this action', null=True)),
                ('performed_by_name', models.CharField(blank=True, help_text='Full name snapshot — preserved even if user is deleted', max_length=200)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS_DENIED', 'Access Denied')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('old_value', models.JSONField(blank=True, help_text='Values BEFORE the change. Null for CREATE actions.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Values AFTER the change. Null for DELETE actions.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ASSET_CONDITION', 'Asset Condition'), ('FUNDING_SOURCE', 'Funding Source'), ('LOCATION_TYPE', 'Location Type'), ('DISPOSAL_METHOD', 'Disposal Method'), ('ACQUISITION_METHOD', 'Acquisition Method')], help_text='Which type of reference data this is', max_length=50)),
                ('value', models.CharField(help_text='The stored code value. Example: GOVT', max_length=100)),
                ('label', models.CharField(help_text='Human-readable display label. Example: Government Budget', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Controls display order in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Data',
                'verbose_name_plural': 'Master Data',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code for this unit. Example: MOH, MNH, RAD', max_length=20)),
                ('unit_type', models.CharField(choices=[('MINISTRY', 'Ministry'), ('AGENCY', 'Agency'), ('FACILITY', 'Facility')], help_text='Level in the hierarchy', max_length=20)),
                ('manager_id', models.IntegerField(blank=True, help_text='ID of the CustomUser who manages this unit', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent unit. Null only for the root Ministry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.orgunit')),
            ],
            options={
                'verbose_name': 'Organisation Unit',
                'verbose_name_plural': 'Organisation Units',
            },
        ),
    ]
