# Generated by Django 6.0.5 on 2026-06-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='category',
            field=models.CharField(choices=[('FUNDING_SOURCE', 'Funding Source'), ('ACQUISITION_METHOD', 'Acquisition Method'), ('LOCATION_TYPE', 'Location Type'), ('DISPOSAL_METHOD', 'Disposal Method'), ('COST_CENTRE', 'Cost Centre')], help_text='Which type of reference data this is', max_length=50),
        ),
    ]
