# Generated by Django 6.0.5 on 2026-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_masterdata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='performed_by_role',
            field=models.CharField(blank=True, help_text='Role of the user at time of action — snapshot', max_length=50),
        ),
    ]
