# Generated by Django 6.0.5 on 2026-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username that was attempted', max_length=150)),
                ('email', models.CharField(blank=True, help_text='Email if provided during login attempt', max_length=254)),
                ('full_name', models.CharField(blank=True, help_text='Full name if available from Keycloak token', max_length=200)),
                ('keycloak_id', models.CharField(blank=True, help_text='Keycloak user ID if SSO was used', max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login attempt', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser or device info', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by_id', models.IntegerField(blank=True, help_text='ID of the admin who reviewed this request', null=True)),
                ('reviewed_by_name', models.CharField(blank=True, help_text='Name of the admin who reviewed this request', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this request was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about this access request')),
            ],
            options={
                'verbose_name': 'Pending Access Request',
                'verbose_name_plural': 'Pending Access Requests',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
