# Generated by Django 6.0.5 on 2026-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='keycloak_id',
            field=models.CharField(blank=True, help_text='Keycloak user UUID — links this Django account to Keycloak', max_length=100, null=True, unique=True),
        ),
    ]
