# Generated by Django 6.0.5 on 2026-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_keycloak_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by_id', models.IntegerField(null=True)),
                ('performed_by_name', models.CharField(blank=True, max_length=200)),
                ('performed_by_role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('PENDING_APPROVED', 'Pending Access Approved'), ('PENDING_REJECTED', 'Pending Access Rejected'), ('USER_CREATED', 'User Created'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('USER_EDITED', 'User Edited'), ('MINISTRY_CREATED', 'Ministry Created'), ('PASSWORD_RESET', 'Password Reset')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('target_username', models.CharField(blank=True, max_length=150)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Super Admin Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
