# Generated by Django 6.0.5 on 2026-07-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_superadminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaccess',
            name='ministry_schema',
            field=models.CharField(blank=True, help_text='Which ministry schema this user was trying to access', max_length=63),
        ),
    ]
