# Generated by Django 6.0.5 on 2026-07-11 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_pending_access_ministry_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked by brute force protection after too many failed attempts'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this attempt record was first created'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='stage',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('COOLDOWN', 'Cooldown'), ('DISABLED', 'Disabled')], default='WARNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Temporary cooldown end time — stage 2 only', null=True),
        ),
        migrations.CreateModel(
            name='UnlockToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unlock Token',
                'verbose_name_plural': 'Unlock Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
